CREATE TEMPORARY TABLE temp_table AS (
 SELECT tag, tags_grades.grade, COUNT(*) count
 FROM (
  SELECT SPLIT(tags, '|') tags
  FROM ${ref("posts_combined")} a
  WHERE DATE(created_at) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 400 DAY) AND CURRENT_DATE()
 ), UNNEST(tags) tag
 LEFT JOIN ${ref("stg_tags")} as tags_grades
   ON tag = tags_grades.tag_name
GROUP BY 1, 2
ORDER BY 3 DESC
LIMIT 10
);

EXPORT temp_table to 'gs://dataform-demo-tags/top_trending_tags.parquet'
FORMAT = 'parquet'
